blank_issues_enabled: false
contact_links:
  - name: "Virtual PowerShell User Group #testing channel"
    url: https://poshcode.org/
    about: "To talk to the community and maintainers of PesterConverter, please visit the #testing channel."
